# Generated by Django 4.2 on 2023-05-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0004_alter_move_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="move",
            name="is_attacking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="move",
            name="is_defending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="move",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("step_order", models.IntegerField()),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="positions.move",
                    ),
                ),
            ],
        ),
    ]
